Feature/room view user admin
Nataliachm/hotel-booking pull request #21
Opened 2023-08-22 19:34 UTC by viamazoba

2023-08-22 19:46 UTC, facamesi52 approved these changes

2023-08-22 20:07 UTC, ht1204 commented on src/components/CardRooms/CardRooms.scss
> +    // padding: 0rem 0.3rem 0rem 0.3rem;
Please, remove commented code.

2023-08-22 20:07 UTC, ht1204 commented on src/components/CardRooms/index.jsx
>    // </div>
same here,

2023-08-22 20:07 UTC, ht1204 commented on src/pages/AdminRoomEdit/AdminRoomEdit.scss
> +        // margin-right: 1rem;
here

2023-08-22 20:07 UTC, ht1204 commented on src/pages/AdminRoomEdit/AdminRoomEdit.scss
> +        margin-bottom: 2rem;
also this couple of lines.

2023-08-22 20:08 UTC, ht1204 commented on src/pages/AdminRoomEdit/index.jsx
> +            // roomName, urlImage, arrayAmenities, arrayInclusions, previousPrice, newPrice,
here

2023-08-22 20:08 UTC, ht1204 commented on src/pages/AdminRoomEdit/infoRooms.js
> +    locationTags: 'Mina Road, Bur Dubai, Dubai, United Arab Emirates', // Clase hotel
Remove unnecessary comments in code.

2023-08-22 20:08 UTC, ht1204 commented on src/pages/UserBookedRooms/UserBookedRooms.scss
> +        // margin-right: 1rem;
remove these ones

2023-08-22 20:08 UTC, ht1204 commented on src/pages/UserBookedRooms/index.jsx
> +  //   dateOut: '5/08/2023',
Please, remove also here.

2023-08-22 20:09 UTC, ht1204 commented on src/pages/UserBookedRooms/index.jsx
> +          img="https://icon-library.com/images/persona-icon/persona-icon-25.jpg"
This image link could be better in an importable constant.

2023-08-22 20:09 UTC, ht1204 commented on src/pages/UserBookedRooms/index.jsx
> +            // roomName, urlImage, arrayAmenities, arrayInclusions, previousPrice, newPrice,
remove this commented line.

2023-08-22 20:09 UTC, ht1204 commented on src/styles/abstract/mixins.scss
>  //     background-color: $background-color;
remove this commented mixin.

2023-08-22 20:09 UTC, ht1204 requested changes
Please, address the comments, thx.

2023-08-22 20:47 UTC, Nataliachm approved these changes

2023-08-22 23:20 UTC, viamazoba commented
Héctor te voy a ser totalmente sincero, creo que tus recomendaciones son valiosas, sin embargo no deberías parar nuestro flujo de trabajo, ya que eso lo podemos tener en cuenta para el próximo pull request que hagamos, ya que no tener comentarios en **este preciso momento** es un nice to have más que un must have.

2023-08-23 02:04 UTC, ht1204 approved these changes

2023-08-23 02:04 UTC, merged